# Generated by Django 3.2.9 on 2021-12-19 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=20)),
                ('timeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('noteHeading', models.TextField()),
                ('noteContent', models.TextField()),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('deadlineDate', models.DateField(blank=True, null=True)),
                ('deadlineTime', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
